/// Eget, enkelt SV/EN-språksystem för GUI:t — INTE Flutters intl-baserade
/// l10n-maskineri (onödigt overhead för två statiska språkkartor som redan
/// finns som Dart-kod). `currentLanguage` sätts av [ConfigProvider] (som
/// äger den sparade preferensen, se `providers/config_provider.dart`) och
/// läses av `tr()` överallt i widget-trädet. Ett språkbyte triggar
/// `notifyListeners()` på `ConfigProvider`, som `MaterialApp.home` redan
/// lyssnar på via en rot-`Consumer` (se `main.dart`) — hela trädet ritas
/// alltså om automatiskt.
library;

enum AppLanguage { sv, en }

AppLanguage currentLanguage = AppLanguage.sv;

/// Slår upp `key` i den aktiva språkkartan. Saknas nyckeln (t.ex. ett
/// missat fall under migrering) returneras nyckeln själv rått, i stället
/// för att krascha — lätt att upptäcka i UI:t, aldrig ett stopp för
/// användaren.
String tr(String key) {
  final dict = _strings[currentLanguage] ?? _strings[AppLanguage.en]!;
  return dict[key] ?? _strings[AppLanguage.en]![key] ?? key;
}

/// Som [tr], men ersätter `{namn}`-platshållare i strängen med värden ur
/// `params`. Används för meddelanden som bär in ett dynamiskt värde (t.ex.
/// en URL eller ett antal) mitt i en annars översatt mening.
String trp(String key, Map<String, String> params) {
  var s = tr(key);
  params.forEach((k, v) {
    s = s.replaceAll('{$k}', v);
  });
  return s;
}

final Map<AppLanguage, Map<String, String>> _strings = {
  AppLanguage.sv: _sv,
  AppLanguage.en: _en,
};

// ---------------------------------------------------------------------
// Svenska
// ---------------------------------------------------------------------
const Map<String, String> _sv = {
  // --- ConfigProvider: status-/felmeddelanden ---
  'provider.status.connecting': 'Ansluter till brandvägg...',
  'provider.status.logged_in': 'Inloggad',
  'provider.error.login_failed': 'Inloggning misslyckades mot {url}',
  'provider.status.updating': 'Uppdaterar…',
  'provider.status.saving_candidate': 'Sparar ändringar i kandidatkonfiguration...',
  'provider.error.save_candidate_failed': 'Kunde inte spara ändring i kandidat',
  'provider.status.discarding': 'Återställer ändringar...',
  'provider.error.get_running_failed': 'Kunde inte hämta körande konfiguration',
  'provider.error.discard_failed': 'Kunde inte återställa ändringar',
  'provider.status.applying': 'Applicerar nftables-regler på brandväggsservern...',
  'provider.status.confirming': 'Bekräftar och committar konfiguration...',
  'provider.error.confirm_failed': 'Bekräftelse misslyckades',
  'provider.status.rolling_back': 'Återställer till senast kända säkra konfiguration...',

  // --- Login-skärmen ---
  'login.subtitle': 'Administrationsgränssnitt',
  'login.url_label': 'Brandväggens adress',
  'login.url_hint': 'https://192.168.1.1:8443',
  'login.username_label': 'Användarnamn',
  'login.password_label': 'Lösenord',
  'login.submit': 'Logga in',
  'login.language_label': 'Språk',

  // --- Huvudnavigation (main_screen.dart) ---
  'nav.dashboard': 'Dashboard',
  'nav.interfaces': 'Interfaces',
  'nav.routing': 'Routing',
  'nav.policies': 'Policies',
  'nav.objects': 'Objekt',
  'nav.sni': 'SNI',
  'nav.vpn': 'VPN',
  'nav.dns': 'DNS',
  'nav.dns_devices': 'DNS-enheter',
  'nav.dhcp': 'DHCP',
  'nav.logging': 'Loggning',
  'nav.ids': 'IDS',
  'nav.services': 'Tjänster',
  'nav.tools': 'Verktyg',
  'nav.settings': 'Settings',

  'main.title': 'SECURITY HARBOR',
  'main.menu_tooltip': 'Meny',
  'main.mode_host': 'LÄGE: VÄRDDATOR',
  'main.online': 'ONLINE',
  'main.online_with_url': 'ONLINE ({url})',
  'main.not_connected': 'EJ ANSLUTEN',
  'main.refresh_tooltip': 'Uppdatera allt (hämta om status och konfiguration)',
  'main.logout_tooltip': 'Logga ut',
  'main.service_alarm_one': 'Tjänsten "{name}" har fastnat i ett fel-läge (failed).',
  'main.service_alarm_many': '{count} tjänster har fastnat i ett fel-läge (failed): {names}.',
  'main.show_services': 'Visa Tjänster',
  'main.safe_apply_banner': 'ÄNDRINGAR APPLICERADE PÅ BRANDVÄGGEN (SAFE APPLY): Automatisk rollback sker om {seconds} sekunder om du inte bekräftar!',
  'main.confirm_commit': 'BEKRÄFTA (COMMIT)',
  'main.confirm_success': 'Konfiguration bekräftad och committad till running.json!',
  'main.confirm_failed': 'Misslyckades bekräfta',
  'main.rollback': 'RULLA TILLBAKA',
  'main.rollback_success': 'Konfigurationen återställd till senast säkra tillstånd.',
  'main.unapplied_banner': 'Du har obekräftade ändringar redo att testas på brandväggen.',
  'main.undo_changes': 'ÅNGRA ÄNDRINGAR',
  'main.undo_dialog_title': 'Ångra ändringar?',
  'main.undo_dialog_body': 'Alla ändringar du gjort sedan senaste applicering kastas bort och konfigurationen återställs till den som just nu kör på brandväggen. Detta går inte att ångra.',
  'main.cancel': 'Avbryt',
  'main.undo_confirm_button': 'Ångra ändringar',
  'main.undo_success': 'Ändringarna återställdes till körande konfiguration.',
  'main.undo_failed_fallback': 'Kunde inte återställa ändringarna.',
  'main.apply_safe': 'APPLICERA (SAFE APPLY)',
  'main.apply_success': 'Ändringar applicerade på brandväggen! Bekräfta (Commit) inom 30s för att behålla dem.',
  'main.apply_failed_fallback': 'Misslyckades applicera konfiguration på brandväggen',

  // --- Settings: språkkort ---
  'settings.language.title': 'Språk',
  'settings.language.body': 'Väljer språk för hela gränssnittet. Sparas på den här enheten/webbläsaren.',
  'settings.language.sv': 'Svenska',
  'settings.language.en': 'Engelska',

  // --- Settings: sidtitel + inloggningskort ---
  'settings.page_title': 'Systeminställningar & Management',
  'settings.login.title': 'Server-inloggning & Agent API',
  'settings.login.url_label': 'Brandväggens Agent URL (IP och Port)',
  'settings.login.username_label': 'Användarnamn',
  'settings.login.password_label': 'Lösenord',
  'settings.login.submit': 'Logga in på Brandväggen',
  'settings.login.snackbar_success': 'Inloggad som {user} på {url}!',
  'settings.login.snackbar_failed': 'Inloggning misslyckades på {url}',
  'settings.login.status_logged_in': 'Status: Inloggad (Token Aktiv)',
  'settings.login.status_logged_out': 'Status: Ej inloggad',
  'settings.rollback_timeout.title': 'Safe Apply Rollback Timeout (Sekunder)',
  'settings.rollback_timeout.body': 'Standard 30 sekunder innan automatisk återställning sker om bekräftelse (Commit) uteblir.',
  'settings.wan_lock.title': 'Hård WAN Management-spärr',
  'settings.wan_lock.body': 'AKTIV PÅ SYSTEMNIVÅ (Inkommande administration på WAN spärras alltid för säkerhet)',

  // --- services_screen.dart ---
  'services.avbryt': 'Avbryt',
  'services.starta_om': 'Starta om',
  'services.agenten_startar_om_logga_in_igen': 'Agenten startar om — logga in igen om en liten stund.',
  'services.tjanster': 'Tjänster',
  'services.kunde_inte_hamta_tjanststatus': 'Kunde inte hämta tjänststatus.',
  'services.uppdatera_status': 'Uppdatera status',
  'services.restart_confirm_title': 'Starta om {name}?',
  'services.restart_confirm_self': 'Det här är administrations-API:t/GUI:t själv. Din session kopplas ner under omstarten (tar normalt bara någon sekund) — logga in igen efteråt.',
  'services.restart_confirm_other': 'Tjänsten stängs ner och startas om. Om den är aktivt konfigurerad (t.ex. DHCP eller DNS på ett gränssnitt som används) kan klienter tappa anslutning en kort stund.',
  'services.status_note': 'Status uppdateras automatiskt var 15:e sekund. En tjänst som inte är konfigurerad (t.ex. OpenVPN avstängt) visas som "Inaktiv" — det är normalt, inte ett fel.',
  'services.status_active': 'Aktiv',
  'services.status_activating': 'Startar...',
  'services.status_reloading': 'Laddar om...',
  'services.status_failed': 'Misslyckad',
  'services.status_inactive': 'Inaktiv',
  'services.restarted': '{name} omstartad.',
  'services.restart_failed': 'Misslyckades: {err}',

  // --- dns_devices_screen.dart ---
  'dns_devices.dns_enheter': 'DNS-enheter',
  'dns_devices.uppdatera': 'Uppdatera',
  'dns_devices.lagg_till_post': 'Lägg till post',
  'dns_devices.inga_manuella_poster_tillagda_annu': 'Inga manuella poster tillagda ännu.',
  'dns_devices.automatisk_registrering_ar_avstangd_enheterna_nedan': 'Automatisk registrering är avstängd — enheterna nedan listas men slås inte upp i DNS förrän du slår på den ovan.',
  'dns_devices.inga_dhcp_enheter_med_vardnamn_hittades': 'Inga DHCP-enheter med värdnamn hittades.',
  'dns_devices.dns_namn': 'DNS-namn',
  'dns_devices.ip': 'IP',
  'dns_devices.granssnitt': 'Gränssnitt',
  'dns_devices.zon': 'Zon',
  'dns_devices.lagg_till_dns_post': 'Lägg till DNS-post',
  'dns_devices.avbryt': 'Avbryt',
  'dns_devices.lagg_till': 'Lägg till',
  'dns_devices.sok_namn_ip_mac': 'Sök namn / IP / MAC',
  'dns_devices.namn_label': 'Namn (exakt, valfri domän)',
  'dns_devices.namn_hint': 't.ex. server1.example.com eller server1',
  'dns_devices.ip_adress_label': 'IP-adress',

  // --- sni_routes_screen.dart ---
  'sni.intern_server': 'Intern server',
  'sni.lokal_openvpn': 'Lokal OpenVPN',
  'sni.namnbaserad_routning_sni': 'Namnbaserad routning (SNI)',
  'sni.ny_regel': '+ Ny regel',
  'sni.laddar': 'Laddar…',
  'sni.lagg_till_mal': 'Lägg till mål',
  'sni.trafik_utan_matchande_namn_t_ex': 'Trafik utan matchande namn (t.ex. OpenVPN, som inte skickar SNI) skickas hit.',
  'sni.avbryt': 'Avbryt',
  'sni.spara': 'Spara',
  'sni.obs_kraver_att_openvpn_ar_aktiverat': 'OBS: kräver att OpenVPN är aktiverat och kör i TCP-läge.',
  'sni.maltyp': 'Måltyp',
  'sni.redigera': 'Redigera',
  'sni.ta_bort': 'Ta bort',
  'sni.ta_bort_mal': 'Ta bort mål',
  'sni.intro_body': 'Tar emot TLS på en port och skickar vidare till olika interna servrar beroende på efterfrågat värdnamn (SNI). Ingen TLS-terminering — certifikaten stannar på servrarna. Suricata inspekterar handskakningen (SNI/JA3/cert).',
  'sni.ny_sni_regel': 'Ny SNI-regel',
  'sni.redigera_sni_regel': 'Redigera SNI-regel',
  'sni.section_regel': 'REGEL',
  'sni.namn': 'Namn',
  'sni.namn_hint': 't.ex. Interna webbservrar',
  'sni.lyssnarport': 'Lyssnarport',
  'sni.extern_ip_valfri': 'Extern IP (valfri)',
  'sni.bind_alla_om_tom': 'bind alla om tom',
  'sni.section_namn_till_server': 'NAMN → INTERN SERVER',
  'sni.section_fallback': 'FALLBACK (SISTA INSTANS)',
  'sni.intern_ip': 'Intern IP',
  'sni.port': 'Port',
  'sni.vardnamn_label': 'Värdnamn (komma-separerade, "*.x.se" stöds)',
  'sni.vardnamn_hint': 't.ex. px1.exempel.se, px2.exempel.se',

  // --- routes_screen.dart ---
  'routes.avbryt': 'Avbryt',
  'routes.ta_bort': 'Ta bort',
  'routes.lat_karnan_valja_rekommenderas': 'Låt kärnan välja (rekommenderas)',
  'routes.statiska_rutter_routing': 'Statiska Rutter (Routing)',
  'routes.ny_rutt': 'Ny rutt',
  'routes.inga_statiska_rutter_definierade': 'Inga statiska rutter definierade.',
  'routes.ta_bort_rutten': 'Ta bort rutten?',
  'routes.granssnitt_valfritt': 'Gränssnitt (valfritt)',
  'routes.aktiverad': 'Aktiverad',
  'routes.spara': 'Spara',
  'routes.redigera_rutt': 'Redigera rutt',
  'routes.ta_bort_rutt': 'Ta bort rutt',
  'routes.intro_body': 'En rutt gör bara nätet NÅBART. Trafik dit tillåts fortfarande bara om det finns en motsvarande Allow-policy under Policies — Default Deny gäller annars som vanligt.',
  'routes.delete_confirm_body': 'Vill du ta bort rutten "{name}"?\n\nÄndringen sparas i kandidaten men slår inte igenom på brandväggen förrän du trycker Applicera.',
  'routes.ny_statisk_rutt': 'Ny statisk rutt',
  'routes.namn_valfritt': 'Namn (valfritt)',
  'routes.namn_hint': 't.ex. Kontorsnät via router',
  'routes.nat_cidr': 'Nät (CIDR)',
  'routes.nat_hint': 't.ex. 192.168.113.0/24',
  'routes.gateway': 'Gateway',
  'routes.gateway_hint': 't.ex. 10.0.0.1',
  'routes.beskrivning_valfritt': 'Beskrivning (valfritt)',
  'routes.error_cidr': 'Nätet måste anges som CIDR, t.ex. 192.168.113.0/24',
  'routes.error_gateway': 'Gateway måste anges, t.ex. 10.0.0.1',

  // --- dashboard_screen.dart ---
  'dashboard.realtid_trafik_bandbredd_per_interface_vlan': 'Realtid Trafik & Bandbredd per Interface / VLAN (1ggr/sek)',
  'dashboard.in_rx': 'IN (RX)',
  'dashboard.ut_tx': 'UT (TX)',
  'dashboard.system': 'System',
  'dashboard.ver': 'Ver: {v}',
  'dashboard.uptime': 'Uptime',
  'dashboard.driftstatus_aktiv': 'Driftstatus: Aktiv',
  'dashboard.cpu': 'CPU',
  'dashboard.karnor': 'Kärnor: {n}',
  'dashboard.minne': 'Minne',
  'dashboard.ram_ledigt': 'RAM: {gb} GB (LEDIGT {pct}%)',
  'dashboard.okonfigurerad': 'Okonfigurerad',

  // --- dns_screen.dart ---
  'dns.stevenblack_hosts_ads_malware_tracking': 'StevenBlack hosts (ads/malware/tracking)',
  'dns.anpassad_url_en_doman_per_rad': 'Anpassad URL (en domän per rad)',
  'dns.inga_domaner_hamtade_annu': 'Inga domäner hämtade ännu.',
  'dns.dns_dns_filtrering': 'DNS & DNS-filtrering',
  'dns.lokal_dns_resolver': 'Lokal DNS-resolver',
  'dns.upplosningslage': 'Upplösningsläge',
  'dns.vidarebefordra_till_upstream_servrar': 'Vidarebefordra till upstream-servrar',
  'dns.sla_upp_sjalv_mot_rot_servrarna': 'Slå upp själv mot rot-servrarna (rekursiv)',
  'dns.dns_over_tls_dot_mot_upstream': 'DNS-over-TLS (DoT) mot upstream',
  'dns.i_rekursivt_lage_slar_servern_upp': 'I rekursivt läge slår servern upp domäner direkt mot DNS-rotens namnservrar istället för att fråga en upstream-leverantör (t.ex. Cloudflare/Google).',
  'dns.spara': 'Spara',
  'dns.kom_ihag_att_applicera_bekrafta_andringarna': 'Kom ihåg att applicera & bekräfta ändringarna för att öppna DNS-porten (53) mot LAN och starta resolvern.',
  'dns.lokal_dns_zon': 'Lokal DNS-zon',
  'dns.registrera_dhcp_tilldelade_enheters_vardnamn_automatiskt': 'Registrera DHCP-tilldelade enheters värdnamn automatiskt i DNS',
  'dns.lagg_till_blocklista': 'Lägg till blocklista',
  'dns.flera_blocklistor_kan_vara_aktiva_samtidigt': 'Flera blocklistor kan vara aktiva samtidigt — de slås ihop till en gemensam lista i Unbound.',
  'dns.inga_domanblocklistor_tillagda_annu': 'Inga domänblocklistor tillagda ännu.',
  'dns.lagg_till_domanblocklista': 'Lägg till domänblocklista',
  'dns.kalltyp': 'Källtyp',
  'dns.listan_hamtas_automatiskt_enligt_intervallet_ovan': 'Listan hämtas automatiskt enligt intervallet ovan. Innehållet syns i vyn efter första hämtningen.',
  'dns.avbryt': 'Avbryt',
  'dns.skapa_hamta_nu': 'Skapa & hämta nu',
  'dns.uppdatera_nu': 'Uppdatera nu',
  'dns.ta_bort': 'Ta bort',
  'dns.blocklist_updated': '"{name}" uppdaterad',
  'dns.blocklist_update_failed': 'Misslyckades uppdatera "{name}" — se felmeddelande på källan',
  'dns.blocked_domains_title': 'Blockerade domäner — {name} ({count})',
  'dns.upstream_label': 'Upstream DNS-servrar (komma-separerade)',
  'dns.tls_hostname_label': 'TLS-hostnamn för verifiering',
  'dns.lokal_domain_label': 'Lokal domän (suffix, t.ex. "lan")',
  'dns.dns_devices_hint': 'Manuella DNS-poster och de registrerade enheterna listas på sidan "DNS-enheter" i vänstermenyn.',
  'dns.namn_label': 'Namn',
  'dns.url_label': 'URL',
  'dns.uppdateringsintervall_label': 'Uppdateringsintervall (timmar)',
  'dns.anpassad_url': 'Anpassad URL',
  'dns.aktiverad': 'Aktiverad',
  'dns.inaktiverad': 'Inaktiverad',

  // --- dhcp_screen.dart ---
  'dhcp.inget_granssnitt_har_dhcp_aktiverat_aktivera': 'Inget gränssnitt har DHCP aktiverat. Aktivera DHCP på ett gränssnitt först.',
  'dhcp.mac_och_ip_maste_anges': 'MAC och IP måste anges.',
  'dhcp.reservation_tillagd_kom_ihag_att_applicera': 'Reservation tillagd. Kom ihåg att applicera konfigurationen.',
  'dhcp.granssnitt_alla': 'Gränssnitt: Alla',
  'dhcp.granssnitt_dhcp_scope': 'Gränssnitt (DHCP-scope)',
  'dhcp.avbryt': 'Avbryt',
  'dhcp.spara_reservation': 'Spara reservation',
  'dhcp.statiska_reservationer': 'Statiska reservationer',
  'dhcp.lagg_till_reservation': 'Lägg till reservation',
  'dhcp.inga_reservationer_lagg_till_manuellt_eller': 'Inga reservationer. Lägg till manuellt, eller tryck på nålen i en rad nedan för att reservera en aktiv lease.',
  'dhcp.dhcp_klienter': 'DHCP-klienter',
  'dhcp.enheter_som_fatt_en_adress_av': 'Enheter som fått en adress av brandväggens DHCP-server (alla gränssnitt utom WAN).',
  'dhcp.rensa': 'Rensa',
  'dhcp.namn': 'Namn',
  'dhcp.ip_adress': 'IP-adress',
  'dhcp.mac_adress': 'MAC-adress',
  'dhcp.granssnitt': 'Gränssnitt',
  'dhcp.zon': 'Zon',
  'dhcp.fick_lease': 'Fick lease',
  'dhcp.utgar': 'Utgår',
  'dhcp.reservera': 'Reservera',
  'dhcp.inga_aktiva_dhcp_utlaningar_enheter_dyker': 'Inga aktiva DHCP-utlåningar. Enheter dyker upp här när de fått en adress av DHCP-servern.',
  'dhcp.inga_klienter_matchar_filtret': 'Inga klienter matchar filtret.',
  'dhcp.sok_namn_ip_eller_mac': 'Sök namn, IP eller MAC',
  'dhcp.reservera_denna_ip_till_mac_adressen': 'Reservera denna IP till MAC-adressen',
  'dhcp.ny_dhcp_reservation': 'Ny DHCP-reservation',
  'dhcp.reservera_ip_till_mac': 'Reservera IP till MAC',
  'dhcp.namn_hostnamn_label': 'Namn / hostnamn',
  'dhcp.namn_hostnamn_hint': 't.ex. Kamera-Entré',
  'dhcp.reserverad_ip_label': 'Reserverad IP',
  'dhcp.reserverad_ip_hint': 't.ex. 192.168.1.50',
  'dhcp.granssnitt_colon': 'Gränssnitt: {name}',

  // --- objects_screen.dart ---
  'objects.spamhaus_drop_kanda_spam_botnat_nat': 'Spamhaus DROP (kända spam/botnät-nät)',
  'objects.spamhaus_edrop_utokad_drop': 'Spamhaus EDROP (utökad DROP)',
  'objects.tor_exit_noder': 'Tor-exit-noder',
  'objects.anpassad_url_en_cidr_ip_per': 'Anpassad URL (en CIDR/IP per rad)',
  'objects.geoip_helt_land_landskod': 'GeoIP — helt land (landskod)',
  'objects.objekt_grupper': 'Objekt & Grupper',
  'objects.skapa_objekt': '+ Skapa Objekt',
  'objects.skapa_grupp': '+ Skapa Grupp',
  'objects.hot_lista_geoip': '+ Hot-lista / GeoIP',
  'objects.inga_sparade_natverksobjekt_annu': 'Inga sparade nätverksobjekt ännu.',
  'objects.inga_varden_hamtade_annu': 'Inga värden hämtade ännu.',
  'objects.ta_bort_objekt': 'Ta bort objekt?',
  'objects.avbryt': 'Avbryt',
  'objects.ta_bort': 'Ta bort',
  'objects.spara': 'Spara',
  'objects.medlemmar': 'MEDLEMMAR',
  'objects.skapa_forst_nagra_objekt_host_natverk': 'Skapa först några objekt (host/nätverk) att gruppera.',
  'objects.kalltyp': 'Källtyp',
  'objects.listan_hamtas_automatiskt_av_brandvaggen_enligt': 'Listan hämtas automatiskt av brandväggen enligt intervallet ovan. Innehållet syns här efter första hämtningen (kan ta en liten stund).',
  'objects.uppdatera_nu': 'Uppdatera nu',
  'objects.redigera': 'Redigera',
  'objects.automatisk_kalla': '  (automatisk källa: {kind})',
  'objects.typ_grupp_medlemmar': 'Typ: GRUPP  |  Medlemmar: {members}',
  'objects.typ_varden': 'Typ: {type}  |  Värden: {values}',
  'objects.anpassad_url': 'Anpassad URL',
  'objects.geoip_land': 'GeoIP-land',
  'objects.updated': '"{name}" uppdaterad',
  'objects.update_failed': 'Misslyckades uppdatera "{name}" — se felmeddelande på objektet',
  'objects.redigera_natverksobjekt': 'Redigera Nätverksobjekt',
  'objects.skapa_nytt_natverksobjekt': 'Skapa nytt Nätverksobjekt',
  'objects.section_objekt': 'OBJEKT',
  'objects.objektnamn': 'Objektnamn',
  'objects.ip_cidr': 'IP / CIDR',
  'objects.komma_separerade': 'komma-separerade',
  'objects.skapad_i_gui': 'Skapad i GUI',
  'objects.redigera_grupp': 'Redigera Grupp',
  'objects.skapa_ny_grupp': 'Skapa ny Grupp',
  'objects.section_grupp': 'GRUPP',
  'objects.gruppnamn': 'Gruppnamn',
  'objects.grupp_colon': 'grupp: {members}',
  'objects.ny_grupp': 'Ny grupp',
  'objects.grupp_skapad_i_gui': 'Grupp skapad i GUI',
  'objects.redigera_hotlista': 'Redigera Hot-lista / GeoIP-objekt',
  'objects.lagg_till_hotlista': 'Lägg till Hot-lista / GeoIP-objekt',
  'objects.section_kalla': 'KÄLLA',
  'objects.uppdateringsintervall_label': 'Uppdateringsintervall (timmar)',
  'objects.automatiskt_uppdaterad': 'Automatiskt uppdaterad ({kind})',

  // --- connections_screen.dart ---
  'conn.anslutningar_loggning': 'Anslutningar & Loggning',
  'conn.rensa_filter': 'Rensa filter',
  'conn.ingen_trafik_matchar_filtret': 'Ingen trafik matchar filtret.',
  'conn.uppdatera_nu': 'Uppdatera nu',
  'conn.col_atgard': 'Åtgärd',
  'conn.col_tid': 'Tid',
  'conn.col_riktning': 'Riktning',
  'conn.col_regel': 'Regel',
  'conn.col_protokoll': 'Protokoll',
  'conn.col_kalla': 'Källa',
  'conn.col_kallans_mac': 'Källans MAC',
  'conn.col_mal': 'Mål',
  'conn.col_malets_mac': 'Målets MAC',
  'conn.col_state_kedja': 'State/Kedja',
  'conn.rader_count': '{n} rader',
  'conn.defaultdeny_dold': 'DefaultDeny dold',
  'conn.dolj_defaultdeny': 'Dölj DefaultDeny',
  'conn.pausad': 'Pausad',
  'conn.pausa': 'Pausa',
  'conn.ip_adress': 'IP-adress',
  'conn.mac_adress': 'MAC-adress',
  'conn.namn_regel_tooltip': 'Söker på namnet på ett sparat Objekt (Host/Network) vars IP matchar källan eller målet,\nOCH på namnet på den brandväggsregel som tillät/nekade trafiken.',
  'conn.namn_regel': 'Namn / Regel',
  'conn.fran_till': 'Från/Till',
  'conn.fran_kalla': 'Från (källa)',
  'conn.till_mal': 'Till (mål)',
  'conn.riktning': 'Riktning',
  'conn.alla': 'Alla',
  'conn.inkommande': 'Inkommande (från WAN)',
  'conn.utgaende': 'Utgående (till WAN)',
  'conn.internt_lokalt': 'Internt/Lokalt',
  'conn.endast_accept': 'Endast Accept',
  'conn.endast_deny': 'Endast Deny',
  'conn.ip_version': 'IP-version',
  'conn.endast_ipv4': 'Endast IPv4',
  'conn.endast_ipv6': 'Endast IPv6',
  'conn.inkommande_kort': 'Inkommande',
  'conn.utgaende_kort': 'Utgående',
  'conn.internt_kort': 'Internt',
};

// ---------------------------------------------------------------------
// English
// ---------------------------------------------------------------------
const Map<String, String> _en = {
  // --- ConfigProvider status/error messages ---
  'provider.status.connecting': 'Connecting to firewall...',
  'provider.status.logged_in': 'Logged in',
  'provider.error.login_failed': 'Login failed against {url}',
  'provider.status.updating': 'Updating…',
  'provider.status.saving_candidate': 'Saving changes to candidate configuration...',
  'provider.error.save_candidate_failed': 'Could not save change to candidate',
  'provider.status.discarding': 'Reverting changes...',
  'provider.error.get_running_failed': 'Could not fetch running configuration',
  'provider.error.discard_failed': 'Could not revert changes',
  'provider.status.applying': 'Applying nftables rules on the firewall server...',
  'provider.status.confirming': 'Confirming and committing configuration...',
  'provider.error.confirm_failed': 'Confirmation failed',
  'provider.status.rolling_back': 'Restoring last known-safe configuration...',

  // --- Login screen ---
  'login.subtitle': 'Admin interface',
  'login.url_label': 'Firewall address',
  'login.url_hint': 'https://192.168.1.1:8443',
  'login.username_label': 'Username',
  'login.password_label': 'Password',
  'login.submit': 'Log in',
  'login.language_label': 'Language',

  // --- Main navigation (main_screen.dart) ---
  'nav.dashboard': 'Dashboard',
  'nav.interfaces': 'Interfaces',
  'nav.routing': 'Routing',
  'nav.policies': 'Policies',
  'nav.objects': 'Objects',
  'nav.sni': 'SNI',
  'nav.vpn': 'VPN',
  'nav.dns': 'DNS',
  'nav.dns_devices': 'DNS devices',
  'nav.dhcp': 'DHCP',
  'nav.logging': 'Logging',
  'nav.ids': 'IDS',
  'nav.services': 'Services',
  'nav.tools': 'Tools',
  'nav.settings': 'Settings',

  'main.title': 'SECURITY HARBOR',
  'main.menu_tooltip': 'Menu',
  'main.mode_host': 'MODE: HOST',
  'main.online': 'ONLINE',
  'main.online_with_url': 'ONLINE ({url})',
  'main.not_connected': 'NOT CONNECTED',
  'main.refresh_tooltip': 'Refresh everything (re-fetch status and configuration)',
  'main.logout_tooltip': 'Log out',
  'main.service_alarm_one': 'The service "{name}" is stuck in a failed state.',
  'main.service_alarm_many': '{count} services are stuck in a failed state: {names}.',
  'main.show_services': 'Show Services',
  'main.safe_apply_banner': 'CHANGES APPLIED TO THE FIREWALL (SAFE APPLY): automatic rollback in {seconds} seconds unless you confirm!',
  'main.confirm_commit': 'CONFIRM (COMMIT)',
  'main.confirm_success': 'Configuration confirmed and committed to running.json!',
  'main.confirm_failed': 'Confirmation failed',
  'main.rollback': 'ROLL BACK',
  'main.rollback_success': 'Configuration restored to the last safe state.',
  'main.unapplied_banner': 'You have unconfirmed changes ready to test on the firewall.',
  'main.undo_changes': 'UNDO CHANGES',
  'main.undo_dialog_title': 'Undo changes?',
  'main.undo_dialog_body': 'All changes you made since the last apply are discarded and the configuration is restored to what is currently running on the firewall. This cannot be undone.',
  'main.cancel': 'Cancel',
  'main.undo_confirm_button': 'Undo changes',
  'main.undo_success': 'The changes were reverted to the running configuration.',
  'main.undo_failed_fallback': 'Could not revert the changes.',
  'main.apply_safe': 'APPLY (SAFE APPLY)',
  'main.apply_success': 'Changes applied to the firewall! Confirm (Commit) within 30s to keep them.',
  'main.apply_failed_fallback': 'Failed to apply configuration to the firewall',

  // --- Settings: language card ---
  'settings.language.title': 'Language',
  'settings.language.body': 'Chooses the language for the whole interface. Saved on this device/browser.',
  'settings.language.sv': 'Swedish',
  'settings.language.en': 'English',

  // --- Settings: page title + login card ---
  'settings.page_title': 'System settings & management',
  'settings.login.title': 'Server login & agent API',
  'settings.login.url_label': "Firewall's agent URL (IP and port)",
  'settings.login.username_label': 'Username',
  'settings.login.password_label': 'Password',
  'settings.login.submit': 'Log in to the firewall',
  'settings.login.snackbar_success': 'Logged in as {user} at {url}!',
  'settings.login.snackbar_failed': 'Login failed at {url}',
  'settings.login.status_logged_in': 'Status: Logged in (token active)',
  'settings.login.status_logged_out': 'Status: Not logged in',
  'settings.rollback_timeout.title': 'Safe Apply rollback timeout (seconds)',
  'settings.rollback_timeout.body': 'Default 30 seconds before automatic rollback if confirmation (commit) is missed.',
  'settings.wan_lock.title': 'Hard WAN management lock',
  'settings.wan_lock.body': 'ACTIVE AT THE SYSTEM LEVEL (incoming administration on WAN is always blocked for security)',

  // --- services_screen.dart ---
  'services.avbryt': 'Cancel',
  'services.starta_om': 'Restart',
  'services.agenten_startar_om_logga_in_igen': 'The agent is restarting — log in again in a moment.',
  'services.tjanster': 'Services',
  'services.kunde_inte_hamta_tjanststatus': 'Could not fetch service status.',
  'services.uppdatera_status': 'Refresh status',
  'services.restart_confirm_title': 'Restart {name}?',
  'services.restart_confirm_self': "This is the admin API/GUI itself. Your session will be disconnected during the restart (usually just a second or so) — log in again afterwards.",
  'services.restart_confirm_other': 'The service will be shut down and restarted. If it is actively configured (e.g. DHCP or DNS on an interface in use), clients may briefly lose connectivity.',
  'services.status_note': 'Status updates automatically every 15 seconds. A service that isn\'t configured (e.g. OpenVPN disabled) shows as "Inactive" — that\'s normal, not an error.',
  'services.status_active': 'Active',
  'services.status_activating': 'Starting...',
  'services.status_reloading': 'Reloading...',
  'services.status_failed': 'Failed',
  'services.status_inactive': 'Inactive',
  'services.restarted': '{name} restarted.',
  'services.restart_failed': 'Failed: {err}',

  // --- dns_devices_screen.dart ---
  'dns_devices.dns_enheter': 'DNS devices',
  'dns_devices.uppdatera': 'Refresh',
  'dns_devices.lagg_till_post': 'Add record',
  'dns_devices.inga_manuella_poster_tillagda_annu': 'No manual records added yet.',
  'dns_devices.automatisk_registrering_ar_avstangd_enheterna_nedan': "Automatic registration is off — the devices below are listed but won't resolve in DNS until you turn it on above.",
  'dns_devices.inga_dhcp_enheter_med_vardnamn_hittades': 'No DHCP devices with a hostname were found.',
  'dns_devices.dns_namn': 'DNS name',
  'dns_devices.ip': 'IP',
  'dns_devices.granssnitt': 'Interface',
  'dns_devices.zon': 'Zone',
  'dns_devices.lagg_till_dns_post': 'Add DNS record',
  'dns_devices.avbryt': 'Cancel',
  'dns_devices.lagg_till': 'Add',
  'dns_devices.sok_namn_ip_mac': 'Search name / IP / MAC',
  'dns_devices.namn_label': 'Name (exact, domain optional)',
  'dns_devices.namn_hint': 'e.g. server1.example.com or server1',
  'dns_devices.ip_adress_label': 'IP address',

  // --- sni_routes_screen.dart ---
  'sni.intern_server': 'Internal server',
  'sni.lokal_openvpn': 'Local OpenVPN',
  'sni.namnbaserad_routning_sni': 'Name-based routing (SNI)',
  'sni.ny_regel': '+ New rule',
  'sni.laddar': 'Loading…',
  'sni.lagg_till_mal': 'Add target',
  'sni.trafik_utan_matchande_namn_t_ex': "Traffic without a matching name (e.g. OpenVPN, which doesn't send SNI) is sent here.",
  'sni.avbryt': 'Cancel',
  'sni.spara': 'Save',
  'sni.obs_kraver_att_openvpn_ar_aktiverat': 'NOTE: requires OpenVPN to be enabled and running in TCP mode.',
  'sni.maltyp': 'Target type',
  'sni.redigera': 'Edit',
  'sni.ta_bort': 'Delete',
  'sni.ta_bort_mal': 'Remove target',
  'sni.intro_body': "Accepts TLS on a port and forwards to different internal servers depending on the requested hostname (SNI). No TLS termination — the certificates stay on the servers. Suricata still inspects the handshake (SNI/JA3/cert).",
  'sni.ny_sni_regel': 'New SNI rule',
  'sni.redigera_sni_regel': 'Edit SNI rule',
  'sni.section_regel': 'RULE',
  'sni.namn': 'Name',
  'sni.namn_hint': 'e.g. Internal web servers',
  'sni.lyssnarport': 'Listen port',
  'sni.extern_ip_valfri': 'External IP (optional)',
  'sni.bind_alla_om_tom': 'bind all if empty',
  'sni.section_namn_till_server': 'NAME → INTERNAL SERVER',
  'sni.section_fallback': 'FALLBACK (LAST RESORT)',
  'sni.intern_ip': 'Internal IP',
  'sni.port': 'Port',
  'sni.vardnamn_label': 'Hostnames (comma-separated, "*.x.se" supported)',
  'sni.vardnamn_hint': 'e.g. px1.example.com, px2.example.com',

  // --- routes_screen.dart ---
  'routes.avbryt': 'Cancel',
  'routes.ta_bort': 'Delete',
  'routes.lat_karnan_valja_rekommenderas': 'Let the kernel choose (recommended)',
  'routes.statiska_rutter_routing': 'Static Routes (Routing)',
  'routes.ny_rutt': 'New route',
  'routes.inga_statiska_rutter_definierade': 'No static routes defined.',
  'routes.ta_bort_rutten': 'Delete the route?',
  'routes.granssnitt_valfritt': 'Interface (optional)',
  'routes.aktiverad': 'Enabled',
  'routes.spara': 'Save',
  'routes.redigera_rutt': 'Edit route',
  'routes.ta_bort_rutt': 'Delete route',
  'routes.intro_body': "A route only makes the network REACHABLE. Traffic to it is still only allowed if there's a matching Allow policy under Policies — Default Deny otherwise applies as usual.",
  'routes.delete_confirm_body': 'Delete the route "{name}"?\n\nThe change is saved to the candidate but won\'t take effect on the firewall until you press Apply.',
  'routes.ny_statisk_rutt': 'New static route',
  'routes.namn_valfritt': 'Name (optional)',
  'routes.namn_hint': 'e.g. Office network via router',
  'routes.nat_cidr': 'Network (CIDR)',
  'routes.nat_hint': 'e.g. 192.168.113.0/24',
  'routes.gateway': 'Gateway',
  'routes.gateway_hint': 'e.g. 10.0.0.1',
  'routes.beskrivning_valfritt': 'Description (optional)',
  'routes.error_cidr': 'The network must be given as CIDR, e.g. 192.168.113.0/24',
  'routes.error_gateway': 'A gateway is required, e.g. 10.0.0.1',

  // --- dashboard_screen.dart ---
  'dashboard.realtid_trafik_bandbredd_per_interface_vlan': 'Real-time Traffic & Bandwidth per Interface / VLAN (1x/sec)',
  'dashboard.in_rx': 'IN (RX)',
  'dashboard.ut_tx': 'OUT (TX)',
  'dashboard.system': 'System',
  'dashboard.ver': 'Ver: {v}',
  'dashboard.uptime': 'Uptime',
  'dashboard.driftstatus_aktiv': 'Status: Active',
  'dashboard.cpu': 'CPU',
  'dashboard.karnor': 'Cores: {n}',
  'dashboard.minne': 'Memory',
  'dashboard.ram_ledigt': 'RAM: {gb} GB (FREE {pct}%)',
  'dashboard.okonfigurerad': 'Unconfigured',

  // --- dns_screen.dart ---
  'dns.stevenblack_hosts_ads_malware_tracking': 'StevenBlack hosts (ads/malware/tracking)',
  'dns.anpassad_url_en_doman_per_rad': 'Custom URL (one domain per line)',
  'dns.inga_domaner_hamtade_annu': 'No domains fetched yet.',
  'dns.dns_dns_filtrering': 'DNS & DNS filtering',
  'dns.lokal_dns_resolver': 'Local DNS resolver',
  'dns.upplosningslage': 'Resolution mode',
  'dns.vidarebefordra_till_upstream_servrar': 'Forward to upstream servers',
  'dns.sla_upp_sjalv_mot_rot_servrarna': 'Resolve directly against the root servers (recursive)',
  'dns.dns_over_tls_dot_mot_upstream': 'DNS-over-TLS (DoT) to upstream',
  'dns.i_rekursivt_lage_slar_servern_upp': 'In recursive mode the server resolves domains directly against the DNS root nameservers instead of asking an upstream provider (e.g. Cloudflare/Google).',
  'dns.spara': 'Save',
  'dns.kom_ihag_att_applicera_bekrafta_andringarna': 'Remember to apply & confirm the changes to open the DNS port (53) to the LAN and start the resolver.',
  'dns.lokal_dns_zon': 'Local DNS zone',
  'dns.registrera_dhcp_tilldelade_enheters_vardnamn_automatiskt': 'Automatically register DHCP-assigned devices\' hostnames in DNS',
  'dns.lagg_till_blocklista': 'Add blocklist',
  'dns.flera_blocklistor_kan_vara_aktiva_samtidigt': 'Several blocklists can be active at once — they are merged into one combined list in Unbound.',
  'dns.inga_domanblocklistor_tillagda_annu': 'No domain blocklists added yet.',
  'dns.lagg_till_domanblocklista': 'Add domain blocklist',
  'dns.kalltyp': 'Source type',
  'dns.listan_hamtas_automatiskt_enligt_intervallet_ovan': 'The list is fetched automatically per the interval above. The content shows in the view after the first fetch.',
  'dns.avbryt': 'Cancel',
  'dns.skapa_hamta_nu': 'Create & fetch now',
  'dns.uppdatera_nu': 'Refresh now',
  'dns.ta_bort': 'Delete',
  'dns.blocklist_updated': '"{name}" updated',
  'dns.blocklist_update_failed': 'Failed to update "{name}" — see the error on the source',
  'dns.blocked_domains_title': 'Blocked domains — {name} ({count})',
  'dns.upstream_label': 'Upstream DNS servers (comma-separated)',
  'dns.tls_hostname_label': 'TLS hostname for verification',
  'dns.lokal_domain_label': 'Local domain (suffix, e.g. "lan")',
  'dns.dns_devices_hint': 'Manual DNS records and registered devices are listed on the "DNS devices" page in the side menu.',
  'dns.namn_label': 'Name',
  'dns.url_label': 'URL',
  'dns.uppdateringsintervall_label': 'Refresh interval (hours)',
  'dns.anpassad_url': 'Custom URL',
  'dns.aktiverad': 'Enabled',
  'dns.inaktiverad': 'Disabled',

  // --- dhcp_screen.dart ---
  'dhcp.inget_granssnitt_har_dhcp_aktiverat_aktivera': 'No interface has DHCP enabled. Enable DHCP on an interface first.',
  'dhcp.mac_och_ip_maste_anges': 'MAC and IP are required.',
  'dhcp.reservation_tillagd_kom_ihag_att_applicera': 'Reservation added. Remember to apply the configuration.',
  'dhcp.granssnitt_alla': 'Interface: All',
  'dhcp.granssnitt_dhcp_scope': 'Interface (DHCP scope)',
  'dhcp.avbryt': 'Cancel',
  'dhcp.spara_reservation': 'Save reservation',
  'dhcp.statiska_reservationer': 'Static reservations',
  'dhcp.lagg_till_reservation': 'Add reservation',
  'dhcp.inga_reservationer_lagg_till_manuellt_eller': 'No reservations. Add one manually, or click the pin on a row below to reserve an active lease.',
  'dhcp.dhcp_klienter': 'DHCP clients',
  'dhcp.enheter_som_fatt_en_adress_av': "Devices that got an address from the firewall's DHCP server (all interfaces except WAN).",
  'dhcp.rensa': 'Clear',
  'dhcp.namn': 'Name',
  'dhcp.ip_adress': 'IP address',
  'dhcp.mac_adress': 'MAC address',
  'dhcp.granssnitt': 'Interface',
  'dhcp.zon': 'Zone',
  'dhcp.fick_lease': 'Leased at',
  'dhcp.utgar': 'Expires',
  'dhcp.reservera': 'Reserve',
  'dhcp.inga_aktiva_dhcp_utlaningar_enheter_dyker': 'No active DHCP leases. Devices appear here once they get an address from the DHCP server.',
  'dhcp.inga_klienter_matchar_filtret': 'No clients match the filter.',
  'dhcp.sok_namn_ip_eller_mac': 'Search name, IP, or MAC',
  'dhcp.reservera_denna_ip_till_mac_adressen': 'Reserve this IP to the MAC address',
  'dhcp.ny_dhcp_reservation': 'New DHCP reservation',
  'dhcp.reservera_ip_till_mac': 'Reserve IP to MAC',
  'dhcp.namn_hostnamn_label': 'Name / hostname',
  'dhcp.namn_hostnamn_hint': 'e.g. Front-door camera',
  'dhcp.reserverad_ip_label': 'Reserved IP',
  'dhcp.reserverad_ip_hint': 'e.g. 192.168.1.50',
  'dhcp.granssnitt_colon': 'Interface: {name}',

  // --- objects_screen.dart ---
  'objects.spamhaus_drop_kanda_spam_botnat_nat': 'Spamhaus DROP (known spam/botnet networks)',
  'objects.spamhaus_edrop_utokad_drop': 'Spamhaus EDROP (extended DROP)',
  'objects.tor_exit_noder': 'Tor exit nodes',
  'objects.anpassad_url_en_cidr_ip_per': 'Custom URL (one CIDR/IP per line)',
  'objects.geoip_helt_land_landskod': 'GeoIP — whole country (country code)',
  'objects.objekt_grupper': 'Objects & Groups',
  'objects.skapa_objekt': '+ Create Object',
  'objects.skapa_grupp': '+ Create Group',
  'objects.hot_lista_geoip': '+ Threat list / GeoIP',
  'objects.inga_sparade_natverksobjekt_annu': 'No saved network objects yet.',
  'objects.inga_varden_hamtade_annu': 'No values fetched yet.',
  'objects.ta_bort_objekt': 'Delete object?',
  'objects.avbryt': 'Cancel',
  'objects.ta_bort': 'Delete',
  'objects.spara': 'Save',
  'objects.medlemmar': 'MEMBERS',
  'objects.skapa_forst_nagra_objekt_host_natverk': 'First create some objects (host/network) to group.',
  'objects.kalltyp': 'Source type',
  'objects.listan_hamtas_automatiskt_av_brandvaggen_enligt': 'The list is fetched automatically by the firewall per the interval above. The content shows here after the first fetch (may take a moment).',
  'objects.uppdatera_nu': 'Refresh now',
  'objects.redigera': 'Edit',
  'objects.automatisk_kalla': '  (automatic source: {kind})',
  'objects.typ_grupp_medlemmar': 'Type: GROUP  |  Members: {members}',
  'objects.typ_varden': 'Type: {type}  |  Values: {values}',
  'objects.anpassad_url': 'Custom URL',
  'objects.geoip_land': 'GeoIP country',
  'objects.updated': '"{name}" updated',
  'objects.update_failed': 'Failed to update "{name}" — see the error on the object',
  'objects.redigera_natverksobjekt': 'Edit Network Object',
  'objects.skapa_nytt_natverksobjekt': 'Create New Network Object',
  'objects.section_objekt': 'OBJECT',
  'objects.objektnamn': 'Object name',
  'objects.ip_cidr': 'IP / CIDR',
  'objects.komma_separerade': 'comma-separated',
  'objects.skapad_i_gui': 'Created in GUI',
  'objects.redigera_grupp': 'Edit Group',
  'objects.skapa_ny_grupp': 'Create New Group',
  'objects.section_grupp': 'GROUP',
  'objects.gruppnamn': 'Group name',
  'objects.grupp_colon': 'group: {members}',
  'objects.ny_grupp': 'New group',
  'objects.grupp_skapad_i_gui': 'Group created in GUI',
  'objects.redigera_hotlista': 'Edit Threat List / GeoIP Object',
  'objects.lagg_till_hotlista': 'Add Threat List / GeoIP Object',
  'objects.section_kalla': 'SOURCE',
  'objects.uppdateringsintervall_label': 'Refresh interval (hours)',
  'objects.automatiskt_uppdaterad': 'Automatically updated ({kind})',

  // --- connections_screen.dart ---
  'conn.anslutningar_loggning': 'Connections & Logging',
  'conn.rensa_filter': 'Clear filter',
  'conn.ingen_trafik_matchar_filtret': 'No traffic matches the filter.',
  'conn.uppdatera_nu': 'Refresh now',
  'conn.col_atgard': 'Action',
  'conn.col_tid': 'Time',
  'conn.col_riktning': 'Direction',
  'conn.col_regel': 'Rule',
  'conn.col_protokoll': 'Protocol',
  'conn.col_kalla': 'Source',
  'conn.col_kallans_mac': "Source's MAC",
  'conn.col_mal': 'Destination',
  'conn.col_malets_mac': "Destination's MAC",
  'conn.col_state_kedja': 'State/Chain',
  'conn.rader_count': '{n} rows',
  'conn.defaultdeny_dold': 'DefaultDeny hidden',
  'conn.dolj_defaultdeny': 'Hide DefaultDeny',
  'conn.pausad': 'Paused',
  'conn.pausa': 'Pause',
  'conn.ip_adress': 'IP address',
  'conn.mac_adress': 'MAC address',
  'conn.namn_regel_tooltip': "Searches the name of a saved object (host/network) whose IP matches the source or destination,\nAND the name of the firewall rule that allowed/denied the traffic.",
  'conn.namn_regel': 'Name / Rule',
  'conn.fran_till': 'From/To',
  'conn.fran_kalla': 'From (source)',
  'conn.till_mal': 'To (destination)',
  'conn.riktning': 'Direction',
  'conn.alla': 'All',
  'conn.inkommande': 'Inbound (from WAN)',
  'conn.utgaende': 'Outbound (to WAN)',
  'conn.internt_lokalt': 'Internal/local',
  'conn.endast_accept': 'Accept only',
  'conn.endast_deny': 'Deny only',
  'conn.ip_version': 'IP version',
  'conn.endast_ipv4': 'IPv4 only',
  'conn.endast_ipv6': 'IPv6 only',
  'conn.inkommande_kort': 'Inbound',
  'conn.utgaende_kort': 'Outbound',
  'conn.internt_kort': 'Internal',
};
